/*
  ____  _       _            _             _       
 / ___|(_)_ __ | | __  _ __ | |_   _  __ _(_)_ __  
 \___ \| | '_ \| |/ / | '_ \| | | | |/ _` | | '_ \ 
  ___) | | | | |   <  | |_) | | |_| | (_| | | | | |
 |____/|_|_| |_|_|\_\ | .__/|_|\__,_|\__, |_|_| |_|
                      |_|            |___/         
# A Template for RerunPlugin, a Sink Plugin
# Generated by the command: plugin -t sink -d rerun rerun
# Hostname: lorenzo-XPS-13-7390
# Current working directory: /home/lorenzo/Documents/github/SUBMIT_RoboticPerception/SIMULATION
# Creation date: 2026-02-18T11:27:37.061+0100
# NOTICE: MADS Version 2.0.0
*/

// Mandatory included headers
#include <sink.hpp>
#include <nlohmann/json.hpp>
#include <pugg/Kernel.h>

// other includes as needed here
// Rerun SDK headers
#include <rerun.hpp>
#include <rerun/archetypes/points3d.hpp>
#include <rerun/archetypes/arrows3d.hpp>
#include <rerun/archetypes/line_strips3d.hpp>
#include <rerun/archetypes/scalars.hpp>

#include <iostream>
#include <vector>
#include <cmath>
#include <deque>
// Define the name of the plugin
#ifndef PLUGIN_NAME
#define PLUGIN_NAME "rerun"
#endif

// Load the namespaces
using namespace std;
using json = nlohmann::json;

// Helper per gestire la history delle traiettorie
struct Trajectory {
    std::deque<rerun::Position3D> points;
    size_t max_size = 5000; // Limite punti per evitare memoria infinita

    void add(float x, float y, float z) {
        points.push_back({x, y, z});
        if (points.size() > max_size) points.pop_front();
    }

    std::vector<rerun::Position3D> to_vector() const {
        return {points.begin(), points.end()};
    }

    void clear() {
        points.clear();
    }
};


// Plugin class. This shall be the only part that needs to be modified,
// implementing the actual functionality
class RerunPlugin : public Sink<json> {

public:

  // Typically, no need to change this
  string kind() override { return PLUGIN_NAME; }

  RerunPlugin() : _rec("MADS_Rerun_Sink") {}

  // Implement the actual functionality here
  // Return types:
  // return_type::success: processing is valid
  // return_type::retry: skip processing go to next loop
  // return_type::warning: content of _error is tracked with register_event
  // return_type::error: _error is traced, skip process
  // return_type::critical: execution stops
  return_type load_data(json const &input, string topic = "") override {
    try {
            // 1. Setup e Time Sync
            // MADS ci passa il JSON già pulito: non servono regex o sanitizzazione!
            if (!input.contains("sim_time") && !input.contains("timecode")) return return_type::retry;
            
            double time_val = input.value("sim_time", input.value("timecode", 0.0));
            _rec.set_time_seconds("sim_time", time_val);

            // Filtraggio Topic (se necessario, configurabile da mads.ini)
            // Qui assumiamo di voler visualizzare tutto quello che arriva
            
            // ---------------------------------------------------------
            // 2. Visualizzazione Odometry Filter
            // ---------------------------------------------------------
            
            // A. FULL EKF (Posizione e Scia Gialla)
            if (input.contains("pose") && input["pose"].contains("position")) {
                auto& pos_vec = input["pose"]["position"];
                float x = (float)pos_vec[0];
                float y = (float)pos_vec[1];
                float z = 0.0f; 

                // Aggiorna scia
                _traj_ekf.add(x, y, z);

                // Log Corpo Robot (Punto Giallo)
                _rec.log("robot/FULL_EKF_body", 
                    rerun::Points3D({{x, y, z}})
                    .with_radii({0.04f})
                    .with_colors({0xFFFF00FF})); // Giallo

                // Log Scia (Linea Gialla)
                _rec.log("robot/FULL_EKF_path", 
                    rerun::LineStrips3D(_traj_ekf.to_vector())
                    .with_colors({0xFFFF00FF})
                    .with_radii({0.01f}));
                
            }

            // B. DEBUG DATA
            if (input.contains("debug")) {
                auto& d = input["debug"];

                // Raw Encoder (Rosso)
                if (d.contains("raw_encoder_only")) {
                    float x = d["raw_encoder_only"][0];
                    float y = d["raw_encoder_only"][1];
                    _traj_raw.add(x, y, 0.0f);

                    _rec.log("robot/raw_encoder_body", 
                        rerun::Points3D({{x, y, 0.0f}})
                        .with_radii({0.04f})
                        .with_colors({0xFF0000FF})); // Rosso
                    
                    _rec.log("robot/raw_encoder_path",
                        rerun::LineStrips3D(_traj_raw.to_vector())
                        .with_colors({0xFF0000FF})
                        .with_radii({0.01f}));
                }

                // Odom Corrected (Verde)
                if (d.contains("Odom_corrected")) {
                    float x = d["Odom_corrected"][0];
                    float y = d["Odom_corrected"][1];
                    _traj_odom_corr.add(x, y, 0.0f);

                    _rec.log("robot/Odom_corrected_body",
                        rerun::Points3D({{x, y, 0.0f}})
                        .with_radii({0.04f})
                        .with_colors({0x00FF00FF}));

                    _rec.log("robot/Odom_corrected_path",
                        rerun::LineStrips3D( _traj_odom_corr.to_vector() )
                        .with_colors({0x00FF00FF})
                        .with_radii({0.01f}));
                }

                // 3. RS Center (Ciano)
                if (d.contains("rs_center")) {
                    float x = d["rs_center"][0];
                    float y = d["rs_center"][1];
                    _traj_rs_center.add(x, y, 0.0f);

                    _rec.log("robot/rs_center_debug",
                        rerun::Points3D({{x, y, 0.0f}})
                        .with_radii({0.02f})
                        .with_colors({0x00FFFFFF})); // Ciano

                    _rec.log("robot/rs_center_path",
                        rerun::LineStrips3D(_traj_rs_center.to_vector())
                        .with_colors({0x00FFFFFF})
                        .with_radii({0.01f}));
                }

                // HTC Position (Ground Truth)
                if (d.contains("htc_position")) {
                    float x = d["htc_position"][0];
                    float y = d["htc_position"][1];
                    _traj_htc.add(x, y, 0.0f);

                    _rec.log("robot/htc_position_debug",
                        rerun::Points3D({{x, y, 0.0f}})
                        .with_colors({0x00FF00FF})
                        .with_radii({0.02f}));

                    _rec.log("robot/htc_position_path",
                        rerun::LineStrips3D(_traj_htc.to_vector())
                        .with_colors({0x00FF00FF})
                        .with_radii({0.01f}));
                }

                // --- SCALARS (Grafici Temporali) ---
                
                // Slip / Accelerazione
                if (d.contains("accel_imu")) _rec.log("debug/slip/accel_imu", rerun::Scalars(d["accel_imu"]));
                if (d.contains("accel_enc")) _rec.log("debug/slip/accel_encoder", rerun::Scalars(d["accel_enc"]));
                if (d.contains("is_slipping")) _rec.log("debug/slip/is_slipping_flag", rerun::Scalars(d["is_slipping"]));
                if (d.contains("angle_ratio")) _rec.log("debug/slip/angle_ratio", rerun::Scalars(d["angle_ratio"]));
                if (d.contains("accel_ratio")) _rec.log("debug/slip/accel_ratio", rerun::Scalars(d["accel_ratio"]));

                // DS Metrics
                if (d.contains("ds")) _rec.log("debug/slip/ds", rerun::Scalars((double)d["ds"]));
                if (d.contains("ds_angle")) _rec.log("debug/slip/ds_angle", rerun::Scalars((double)d["ds_angle"]));
                if (d.contains("ds_accel")) _rec.log("debug/slip/ds_accel", rerun::Scalars((double)d["ds_accel"]));
                if (d.contains("ds_final")) _rec.log("debug/slip/ds_final", rerun::Scalars((double)d["ds_final"]));
                
                if (d.contains("current_gyro_z")) _rec.log("debug/slip/current_gyro_z", rerun::Scalars((double)d["current_gyro_z"]));
                if (d.contains("fused_velocity")) _rec.log("fusion/debug/velocity_fused", rerun::Scalars((double)d["fused_velocity"]));

                // Angoli
                if (d.contains("angles")) {
                    auto& ang = d["angles"];
                    if (ang.contains("theta_enc")) _rec.log("debug/angles/theta_encoder", rerun::Scalars(ang["theta_enc"]));
                    if (ang.contains("theta_imu")) _rec.log("debug/angles/theta_imu", rerun::Scalars(ang["theta_imu"]));
                    if (ang.contains("theta_rs")) _rec.log("debug/angles/theta_rs", rerun::Scalars(ang["theta_rs"]));
                    if (ang.contains("fused_full")) _rec.log("debug/angles/fused_full", rerun::Scalars(ang["fused_full"]));
                    if (ang.contains("fused_partial")) _rec.log("debug/angles/fused_partial", rerun::Scalars((double)ang["fused_partial"]));
                    if (ang.contains("htc_angle")) _rec.log("debug/angles/htc_angle", rerun::Scalars((double)ang["htc_angle"]));
                }
            }

            // C. EVALUATION
            if (input.contains("evaluation")) {
                auto& ev = input["evaluation"];
                if (ev.contains("rmse_dist")) _rec.log("evaluation/rmse_distance", rerun::Scalars(ev["rmse_dist"]));
                if (ev.contains("current_error_dist")) _rec.log("evaluation/error_distance", rerun::Scalars(ev["current_error_dist"]));
            }

        } catch (const std::exception &e) {
            std::cerr << "[RerunSink] Parsing Error: " << e.what() << std::endl;
            // Non crashare, continua col prossimo pacchetto
            return return_type::warning;
        }
    return return_type::success;
  }

  void set_params(const json &params) override { 
    // Call the parent class method to set the common parameters 
    // (e.g. agent_id, etc.)
    Sink::set_params(params);

    _params.merge_patch(params);

        // Inizializzazione Rerun
        // Spawn() apre automaticamente il viewer o si connette se aperto
        std::cout << "[RerunSink] Spawning Rerun Viewer..." << std::endl;
        _rec.spawn().exit_on_failure();
        
        // Pulizia traiettorie all'avvio
        _traj_ekf.clear();
        _traj_raw.clear();
        _traj_odom_corr.clear();
        _traj_rs_center.clear();
        _traj_htc.clear();
    
  }

  // Implement this method if you want to provide additional information
  map<string, string> info() override { 
    // return a map of strings with additional information about the plugin
    // it is used to print the information about the plugin when it is loaded
    // by the agent
    return {{"Description", "Native Rerun Visualization Sink for MADS"}}; 
  };

private:
  // Define the fields that are used to store internal resources
  rerun::RecordingStream _rec;
    
    // Storico traiettorie per disegnare le scie (LineStrips)
    Trajectory _traj_ekf;
    Trajectory _traj_raw;
    Trajectory _traj_odom_corr;
    Trajectory _traj_rs_center;
    Trajectory _traj_htc;
  
};



/*
  ____  _             _             _      _                
 |  _ \| |_   _  __ _(_)_ __     __| |_ __(_)_   _____ _ __ 
 | |_) | | | | |/ _` | | '_ \   / _` | '__| \ \ / / _ \ '__|
 |  __/| | |_| | (_| | | | | | | (_| | |  | |\ V /  __/ |   
 |_|   |_|\__,_|\__, |_|_| |_|  \__,_|_|  |_| \_/ \___|_|   
                |___/                                      
Enable the class as plugin 
*/
INSTALL_SINK_DRIVER(RerunPlugin, json)


/*
                  _
  _ __ ___   __ _(_)_ __
 | '_ ` _ \ / _` | | '_ \
 | | | | | | (_| | | | | |
 |_| |_| |_|\__,_|_|_| |_|

For testing purposes, when directly executing the plugin
*/
int main(int argc, char const *argv[]) {
  RerunPlugin plugin;
  json input, params;
  
  // Set the parameters
  plugin.set_params(params);

  // Process data
  plugin.load_data(input);

  return 0;
}
