/*
  _____ _ _ _                    _             _       
 |  ___(_) | |_ ___ _ __   _ __ | |_   _  __ _(_)_ __  
 | |_  | | | __/ _ \ '__| | '_ \| | | | |/ _` | | '_ \ 
 |  _| | | | ||  __/ |    | |_) | | |_| | (_| | | | | |
 |_|   |_|_|\__\___|_|    | .__/|_|\__,_|\__, |_|_| |_|
                          |_|            |___/         
# A Template for Example_filterPlugin, a Filter Plugin
# Generated by the command: plugin -t filter -d example_filter example_filter
# Hostname: lorenzo-XPS-13-7390
# Current working directory: /home/lorenzo/Documents/github/Robotic-Perception-and-action_Project/SIMULATION
# Creation date: 2025-11-27T17:06:49.221+0100
# NOTICE: MADS Version 1.4.0
*/
// Mandatory included headers
#include <filter.hpp>
#include <nlohmann/json.hpp>
#include <pugg/Kernel.h>

// other includes as needed here

// Define the name of the plugin
#ifndef PLUGIN_NAME
#define PLUGIN_NAME "example_filter"
#endif

// Load the namespaces
using namespace std;
using json = nlohmann::json;

void push_value(std::array<double, 3> &vec, double new_value) {
  vec[2] = vec[1];
  vec[1] = vec[0];
  vec[0] = new_value;
}


// Plugin class. This shall be the only part that needs to be modified,
// implementing the actual functionality
class Example_filterPlugin : public Filter<json, json> {

public:

  // Typically, no need to change this
  string kind() override { return PLUGIN_NAME; }

  // Implement the actual functionality here
  return_type load_data(json const &input, string topic = "") override {
    // Do something with the input data
    std::vector<double> vector_extracted = input["message"].value<std::vector<double>>("accel",{});
    push_value(_raw_data, vector_extracted[0]);

    return return_type::success;
  }

  // We calculate the average of the last N values for each key and store it
  // into the output json object
  return_type process(json &out) override {
    out.clear();

    // load the data as necessary and set the fields of the json out variable
    _filtered_data[0] = (_b0*_raw_data[0] + _b1*_raw_data[1] + _b2*_raw_data[2]
                        - _a1*_filtered_data[1] - _a2*_filtered_data[2])/_a0;

    out["filtered_data"] = _filtered_data[0];
    push_value(_filtered_data, 0.0);


    // This sets the agent_id field in the output json object, only when it is
    // not empty
    if (!_agent_id.empty()) out["agent_id"] = _agent_id;
    return return_type::success;
  }
  
  void set_params(void const *params) override {
    // Call the parent class method to set the common parameters 
    // (e.g. agent_id, etc.)
    Filter::set_params(params);

    // provide sensible defaults for the parameters by setting e.g.
    _a0 = _params.value("a0", 1.0);
    _a1 = _params.value("a1", 1.0);
    _a2 = _params.value("a2", 1.0);
    _b0 = _params.value("b0", 1.0);
    _b1 = _params.value("b1", 1.0);
    _b2 = _params.value("b2", 1.0);
    // more here...

    // then merge the defaults with the actually provided parameters
    // params needs to be cast to json
    _params.merge_patch(*(json *)params);
      
  }

  // Implement this method if you want to provide additional information
  map<string, string> info() override { 
    // return a map of strings with additional information about the plugin
    // it is used to print the information about the plugin when it is loaded
    // by the agent
    
    return {};
    
  };

private:
  // Define the fields that are used to store internal resources
  std::array<double, 3> _raw_data = {0.0, 0.0, 0.0};
  std::array<double, 3> _filtered_data = {0.0, 0.0, 0.0};
  double _a0 = 1.0, _a1 = 1.0, _a2 = 1.0,_b0 = 1.0, _b1 = 1.0, _b2 = 1.0;
  
};


/*
  ____  _             _             _      _
 |  _ \| |_   _  __ _(_)_ __     __| |_ __(_)_   _____ _ __
 | |_) | | | | |/ _` | | '_ \   / _` | '__| \ \ / / _ \ '__|
 |  __/| | |_| | (_| | | | | | | (_| | |  | |\ V /  __/ |
 |_|   |_|\__,_|\__, |_|_| |_|  \__,_|_|  |_| \_/ \___|_|
                |___/
Enable the class as plugin
*/
INSTALL_FILTER_DRIVER(Example_filterPlugin, json, json);


/*
                  _       
  _ __ ___   __ _(_)_ __  
 | '_ ` _ \ / _` | | '_ \ 
 | | | | | | (_| | | | | |
 |_| |_| |_|\__,_|_|_| |_|
                          
*/

int main(int argc, char const *argv[])
{
  Example_filterPlugin plugin;
  json params;
  json input, output;

  // Set example values to params
  params["test"] = "value";

  // Set the parameters
  plugin.set_params(&params);

  // Set input data
  input["data"] = {
    {"AX", 1},
    {"AY", 2},
    {"AZ", 3}
  };

  // Set input data
  plugin.load_data(input);
  cout << "Input: " << input.dump(2) << endl;

  // Process data
  plugin.process(output);
  cout << "Output: " << output.dump(2) << endl;


  return 0;
}

